In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.simplefilter("ignore")

In [2]:
movies_data=pd.read_csv('anime.csv')
movies_data.head(3)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262


In [3]:
movies_data.reset_index(inplace=True)
movies_data.head(2)

,index,anime_id,name,genre,type,episodes,rating,members
0,0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665


In [4]:
movies_data.shape

(12294, 8)

In [5]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   index     12294 non-null  int64  
 1   anime_id  12294 non-null  int64  
 2   name      12294 non-null  object 
 3   genre     12232 non-null  object 
 4   type      12269 non-null  object 
 5   episodes  12294 non-null  object 
 6   rating    12064 non-null  float64
 7   members   12294 non-null  int64  
dtypes: float64(1), int64(3), object(4)
memory usage: 768.5+ KB


In [6]:
movies_data.isnull().sum()

index         0
anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [7]:
# selecting the relevant features for recommendation

selected_features = ['genre','type','rating']
print(selected_features)

['genre', 'type', 'rating']


In [8]:
# replacing the null valuess with null string

for features in selected_features:
    movies_data[features]=movies_data[features].fillna('')

In [9]:
# combining all the 5 selected features

combined_features = movies_data['genre']+' '+movies_data['type']

In [10]:
print(combined_features)

0               Drama, Romance, School, Supernatural Movie
1        Action, Adventure, Drama, Fantasy, Magic, Mili...
2        Action, Comedy, Historical, Parody, Samurai, S...
3                                      Sci-Fi, Thriller TV
4        Action, Comedy, Historical, Parody, Samurai, S...
                               ...                        
12289                                           Hentai OVA
12290                                           Hentai OVA
12291                                           Hentai OVA
12292                                           Hentai OVA
12293                                         Hentai Movie
Length: 12294, dtype: object


### Convert the Text Data into Vectors

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
feature_vectors=vectorizer.fit_transform(combined_features)
print(feature_vectors)

  (0, 8)	0.4064272010487408
  (0, 34)	0.4527152773385316
  (0, 36)	0.47908849608944204
  (0, 46)	0.5025939149322276
  (0, 24)	0.384368804014889
  (1, 8)	0.3249918844190286
  (1, 0)	0.2851370263052738
  (1, 1)	0.3073533011726408
  (1, 10)	0.3092912941250856
  (1, 20)	0.4351161402236701
  (1, 23)	0.5047112391013231
  (1, 40)	0.3396562864271053
  (1, 48)	0.2520399009293464
  (2, 0)	0.2446984961974193
  (2, 40)	0.2914857589337753
  (2, 48)	0.21629525122818785
  (2, 5)	0.19601345139698537
  (2, 15)	0.36989945843667305
  (2, 30)	0.4374107864568645
  (2, 35)	0.5377197655779328
  (2, 37)	0.2762765260670507
  (2, 11)	0.2762765260670507
  (3, 48)	0.29229640552335473
  (3, 37)	0.3733537146161548
  (3, 11)	0.3733537146161548
  :	:
  (12282, 14)	0.8251404752084168
  (12283, 29)	0.5649276025941982
  (12283, 14)	0.8251404752084168
  (12284, 29)	0.5649276025941982
  (12284, 14)	0.8251404752084168
  (12285, 46)	0.4853519692839578
  (12285, 29)	0.32315453904991537
  (12285, 7)	0.661223990047087
  (12285

### Cosine Similarity

In [12]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.13208554 0.         ... 0.         0.         0.23759902]
 [0.13208554 1.         0.22329261 ... 0.         0.         0.        ]
 [0.         0.22329261 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         1.         0.64860762]
 [0.         0.         0.         ... 1.         1.         0.64860762]
 [0.23759902 0.         0.         ... 0.64860762 0.64860762 1.        ]]


In [13]:
print(similarity.shape)

(12294, 12294)


In [14]:
# creating a list with all the movie names given in the dataset

list_of_all_titles=movies_data['name'].tolist()
print(list_of_all_titles)

['Kimi no Na wa.', 'Fullmetal Alchemist: Brotherhood', 'Gintama°', 'Steins;Gate', 'Gintama&#039;', 'Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou', 'Hunter x Hunter (2011)', 'Ginga Eiyuu Densetsu', 'Gintama Movie: Kanketsu-hen - Yorozuya yo Eien Nare', 'Gintama&#039;: Enchousen', 'Clannad: After Story', 'Koe no Katachi', 'Gintama', 'Code Geass: Hangyaku no Lelouch R2', 'Haikyuu!! Second Season', 'Sen to Chihiro no Kamikakushi', 'Shigatsu wa Kimi no Uso', 'Mushishi Zoku Shou 2nd Season', 'Ookami Kodomo no Ame to Yuki', 'Code Geass: Hangyaku no Lelouch', 'Hajime no Ippo', 'Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen', 'Cowboy Bebop', 'One Punch Man', 'Mononoke Hime', 'Suzumiya Haruhi no Shoushitsu', 'Monogatari Series: Second Season', 'Mushishi Zoku Shou', 'Mushishi', 'Tengen Toppa Gurren Lagann', 'Great Teacher Onizuka', 'Natsume Yuujinchou Go', 'Hajime no Ippo: New Challenger', 'Mushishi Zoku Shou: Suzu no Shizuku', 'Natsume Yuujinchou Shi', 'Howl no Ugoku Shiro',

In [15]:
# getting the movie name from the user

anime_name = input(' Enter your favourite anime name : ')

 Enter your favourite anime name :  One Piece


In [16]:
# finding the close match for the movie name given by the user
import difflib
find_close_match=difflib.get_close_matches(anime_name,list_of_all_titles)
print(find_close_match)

['One Piece', 'One Piece Recap', 'Piece']


In [17]:
close_match=find_close_match[0]
print(close_match)

One Piece


In [18]:
# finding the index of the movie with title

index_of_the_movie=movies_data[movies_data.name==close_match]['index'].values[0]
print(index_of_the_movie)


74


In [19]:
# getting a list of similar movies

similarity_score=list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.1260902209026329), (1, 0.5307065454373954), (2, 0.2558960148133461), (3, 0.07032648284190052), (4, 0.2558960148133461), (5, 0.38125090199796524), (6, 0.8769467480520614), (7, 0.10585999463398856), (8, 0.20157164853758006), (9, 0.2558960148133461), (10, 0.25308288666361456), (11, 0.3102915199472872), (12, 0.2558960148133461), (13, 0.6028215881151813), (14, 0.38125090199796524), (15, 0.2828315833923649), (16, 0.3153870664383824), (17, 0.1973642861089956), (18, 0.11501375995211348), (19, 0.5091683355581976), (20, 0.4279971476986122), (21, 0.14133163895529283), (22, 0.4058631820508396), (23, 0.527676856490884), (24, 0.4283565284215892), (25, 0.04905246179470907), (26, 0.10560159948466796), (27, 0.1973642861089956), (28, 0.1973642861089956), (29, 0.34014158071951694), (30, 0.33440433841930284), (31, 0.24390790025865558), (32, 0.4279971476986122), (33, 0.14643910435383253), (34, 0.24390790025865558), (35, 0.3910378381796876), (36, 0.24546340443476106), (37, 0.07674259255413259), (38, 

In [20]:
# sorting the movies based on their similarity score

sorted_similar_movies=sorted(similarity_score,key= lambda x:x[1],reverse=True)
print(sorted_similar_movies)

[(74, 1.0000000000000002), (86, 0.9307920610777507), (10899, 0.9307920610777507), (231, 0.9187795787027142), (241, 0.9187795787027142), (896, 0.9187795787027142), (352, 0.8861638360896128), (2161, 0.8861638360896128), (3839, 0.8861638360896128), (6, 0.8769467480520614), (112, 0.8769467480520614), (9673, 0.8769467480520614), (941, 0.8762015401836133), (1171, 0.8762015401836133), (1793, 0.8762015401836133), (2202, 0.8762015401836133), (2492, 0.8762015401836133), (2723, 0.8762015401836133), (3202, 0.8762015401836133), (753, 0.865477934309256), (1576, 0.865477934309256), (1795, 0.865477934309256), (1829, 0.865477934309256), (2119, 0.865477934309256), (3264, 0.865477934309256), (717, 0.8649331373586033), (961, 0.8548008389285093), (1069, 0.8548008389285093), (175, 0.8546879718194256), (3533, 0.8439103596554896), (1289, 0.8364740329695322), (1428, 0.8364740329695322), (7125, 0.8264081888078237), (5264, 0.8210167736455589), (2167, 0.8171440848709528), (10398, 0.8154713008877423), (2933, 0.814

In [21]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['name'].values[0]
  if (i<11):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . One Piece
2 . Shingeki no Kyojin
3 . Shingeki no Kyojin Season 2
4 . One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari
5 . One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna
6 . One Piece: Episode of Sabo - 3 Kyoudai no Kizuna Kiseki no Saikai to Uketsugareru Ishi
7 . One Piece Film: Strong World Episode 0
8 . One Piece Recap
9 . One Piece: Taose! Kaizoku Ganzack
10 . Hunter x Hunter (2011)


# Smart Anime Finder

In [26]:
anime_name = input(' Enter your favourite anime name : ')

list_of_all_titles = movies_data['name'].tolist()

find_close_match = difflib.get_close_matches(anime_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.name == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Animes suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['name'].values[0]
  if (i<11):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite anime name :  Death Note


Animes suggested for you : 

1 . Death Note
2 . Mousou Dairinin
3 . Death Note Rewrite
4 . Higurashi no Naku Koro ni Kai
5 . Mirai Nikki (TV)
6 . Higurashi no Naku Koro ni Rei
7 . Higurashi no Naku Koro ni
8 . Monster
9 . Mirai Nikki (TV): Ura Mirai Nikki
10 . Zankyou no Terror
